# Site settings
name: Richard Chen
title: Richard Chen | Software Engineer
description: Software Engineer and computer science student at Stanford University.
url: https://richarddchen.com/
baseurl: ''
email: richchen@stanford.edu
cover: https://richarddchen.com/img/og.png
logo: https://richarddchen.com/img/emojis/technologist.png
resume: https://richarddchen.com/resume.pdf
social:
  - title: email
    url: mailto:richchen@stanford.edu
  - title: github
    url: https://github.com/chenner45
  - title: linkedin
    url: https://www.linkedin.com/in/richarddchen

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
